name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code of the repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install sshpass
        run: sudo apt install sshpass
      - name: ls -lha
        run: ls -lha
      - name: deploy
        run: sshpass -p ${{ secrets.SERVER_PASSWORD }} scp ./build ${{ secrets.SERVER_USER }}@${{secrets.SERVER_IP}}:/var/www/frontend
